version: '2'
services:
  api:
    build: .
    command: npm start
    volumes:
      - .:/opt/app/
      - /opt/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_PASSWORD: "password"